// A simple random generator is obtained by the formula
// (
// )
// rnew = a ⋅ rold + b %m
// and then setting rold to rnew. If m is chosen as 2^32, then you can compute
// rnew = a ⋅ rold + b
// because the truncation of an overflowing result to the int type is equivalent to
// computing the remainder.
// Write a program that asks the user to enter a seed value for rold. (Such a value is often
// called a seed). Then print the first 100 random integers generated by this formula,
// using a = 32310901 and b = 1729.

import java.util.Scanner;

public class Pro11 {
  public static void main(String[] args) {
    final int A = 32310901;
    final int B = 1729;

    final int ITERATIONS = 5;

    Scanner scanner = new Scanner(System.in);
    System.out.print("Enter an int as seed: ");
    int r_old = scanner.nextInt();

    for (int i = 0; i < ITERATIONS; i++) {
      r_old = A * r_old + B;

      System.out.println(r_old);
    }

    scanner.close();
  }
}
